apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex-media-server
resources:
- cron-jobs
- deployment.yaml
- namespace.yaml
- pvc.yaml
- ../../../../templates/backup/cloudflare-proxy
