apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-server-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 350Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-server-backup
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: /backup/restic/at1-plex-media-server
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-server-backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: plex-media-server-backup
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-server-library
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: /multimedia
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-server-library
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: plex-media-server-library
  storageClassName: ""
