apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcpd
  labels:
    app: dhcpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhcpd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dhcpd
    spec:
      initContainers:
        - name: install-config
          image: alpine:3.19.0
          args: ["eno1"]
          command:
            - "sh"
            - "-c"
            - "cp /etc/dhcpd.conf /data"
          volumeMounts:
            - mountPath: /etc/dhcpd.conf
              name: config
              subPath: dhcpd.conf
            - mountPath: /data
              name: data
      containers:
        - name: dhcpd
          image: networkboot/dhcpd:1.3.0
          volumeMounts:
            - name: data
              mountPath: /data
      hostNetwork: true
      volumes:
        - name: config
          configMap:
            name: dhcpd
        - name: data
          hostPath:
            path: /var/dhcpd
