apiVersion: v1
kind: Service
metadata:
  name: esphome
  labels:
    app: esphome
spec:
  selector:
    app: esphome
  ports:
    - protocol: TCP
      name: esphome
      port: 6052
      targetPort: 6052
