apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
- database/pvc.yaml
- database/service.yaml
- database/statefulset.yaml
- immich/pvc.yaml
- immich/service.yaml
- immich/statefulset.yaml
- redis/pvc.yaml
- redis/deployment.yaml
- redis/service.yaml
- namespace.yaml
