apiVersion: v1
kind: Service
metadata:
  name: unifi-network-server
spec:
  type: ClusterIP
  selector:
    app: unifi-network-server
  ports:
    - name: device-inform
      port: 8080
      targetPort: 8080
    - name: web-https
      port: 8443
      targetPort: 8443
    - name: http-portal
      port: 8880
      targetPort: 8880
    - name: https-portal
      port: 8843
      targetPort: 8843
    - name: stun
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: ap-discovery
      port: 10001
      targetPort: 10001
      protocol: UDP
    - name: speedtest
      port: 6789
      targetPort: 6789
