apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-backup
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 127.0.0.1
    path: /backup/restic/at1-immich
  persistentVolumeReclaimPolicy: Retain
