apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-backup
spec:
  schedule: "30 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: esphome-data
            - name: backup
              persistentVolumeClaim:
                claimName: esphome-backup
