apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq
  labels:
    app: dnsmasq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dnsmasq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dnsmasq
    spec:
      containers:
        - name: dnsmasq
          image: strm/dnsmasq
          args: ["-d"]
          volumeMounts:
            - mountPath: /etc/dnsmasq.conf
              name: config
              subPath: dnsmasq.conf
      hostNetwork: true
      volumes:
        - configMap:
            name: dnsmasq
          name: config
