apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 350Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: immich-backup
  storageClassName: ""
