apiVersion: v1
kind: Service
metadata:
  name: immich
  labels:
    app: immich
spec:
  selector:
    app: immich
  ports:
    - protocol: TCP
      name: immich
      port: 80
      targetPort: 2283
---
apiVersion: v1
kind: Service
metadata:
  name: immich-local
  labels:
    app: immich
spec:
  type: NodePort
  selector:
    app: immich
  ports:
    - protocol: TCP
      name: immich
      port: 2283
      targetPort: 2283
      nodePort: 32283
