apiVersion: v1
kind: Service
metadata:
  name: immich
  labels:
    app: immich
spec:
  selector:
    app: immich
  ports:
    - protocol: TCP
      name: immich
      port: 80
      targetPort: 2283
