apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich
spec:
  serviceName: immich
  replicas: 1
  selector:
    matchLabels:
      app: immich
  template:
    metadata:
      labels:
        app: immich
    spec:
      initContainers:
        - name: restic-backup-restore
          image: ghcr.io/infinityvault/restic-backup:0.0.2
          args: ["restore"]
          envFrom:
            - secretRef:
                name: restic-backup
          env:
            - name: RESTIC_HOST
              value: kubernetes
            - name: RESTIC_REPOSITORY
              value: /backup
          volumeMounts:
            - name: backup
              mountPath: /backup
              readOnly: true
            - name: data
              mountPath: /data
      containers:
        - name: immich
          image: ghcr.io/immich-app/immich-server:v2.0.1
          env:
            - name: IMMICH_PORT
              value: "2283"
            - name: DB_HOSTNAME
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_DB
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOSTNAME
              value: redis
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 2283
          volumeMounts:
            - name: data
              mountPath: /usr/src/app/upload
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: immich-data
        - name: backup
          persistentVolumeClaim:
            claimName: immich-backup
