apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
    - protocol: TCP
      name: home-assistant
      port: 8123
      targetPort: 8123
